image: alpine/edge
packages:
  - deno
secrets:
  - 0323bc6f-a046-4b96-8496-2bac6e7ee107
  - 6a295705-4fb6-451c-990c-9a12b0aa0dc2
sources:
  - git+ssh://git@git.sr.ht/~timharek/deno-linkding
environment:
  DIR: deno-linkding
triggers:
  - action: email
    condition: failure
    to: tim@harek.no
tasks:
  - test: |
      cd $DIR
      deno task check
  - check: |
      cd $DIR
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - new_release: |
      set +x
      export JSR_API=$(cat ~/jsr_timharek)
      cd $dir
      deno publish --allow-slow-types --token $JSR_API
      set -x
  - mirror: |
      cd $DIR
      git remote add github git@github.com:timharek/deno-linkding.git
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git push github main
      if [ "$(git describe --exact-match --tags HEAD)" ]; then \
        git push --tags github; \
      fi

